
## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 1.0
#  - nightly
notifications:
  email: false
git:
  depth: 99999999

## uncomment the following lines to allow failures on nightly julia
## (tests will run but not make your overall status red)
matrix:
  allow_failures:
  - julia: nightly

## uncomment following lines to deploy documentation
jobs:
  include:
    - stage: "Documentation"
      julia: 1.0
      os: linux
      # disable global before_script in order not to install Compose twice
      before_script:
      script:
        - |
          julia --color=yes --project=docs/ -e'
            using Pkg
            Pkg.add(PackageSpec(name="Documenter", rev="master"));Pkg.clone("https://github.com/wildart/TOML.jl");Pkg.clone("https://github.com/alan-turing-institute/MLJBase.jl");Pkg.clone("https://github.com/alan-turing-institute/MLJModels.jl")
            Pkg.develop(PackageSpec(path=pwd()))
            Pkg.instantiate()
            include("docs/make.jl")
          '
after_success: skip
