
[GaussianProcesses.GPClassifier]
":input_is_multivariate" = "`true`"
":package_uuid" = "891a1506-143c-57d2-908e-e1f8e92e6de9"
":load_path" = "MLJModels.GaussianProcesses_.GPClassifier"
":input_scitypes" = "`MLJBase.Continuous`"
":is_pure_julia" = "`true`"
":is_supervised" = "`true`"
":package_url" = "https://github.com/STOR-i/GaussianProcesses.jl"
":package_name" = "GaussianProcesses"
":name" = "GPClassifier"
":is_probabilistic" = "`false`"
":target_scitype" = "`MLJBase.FiniteOrderedFactor`"

[DecisionTree.DecisionTreeClassifier]
":input_is_multivariate" = "`true`"
":package_uuid" = "7806a523-6efd-50cb-b5f6-3fa6f1930dbb"
":load_path" = "MLJModels.DecisionTree_.DecisionTreeClassifier"
":input_scitypes" = "`MLJBase.Continuous`"
":is_pure_julia" = "`true`"
":is_supervised" = "`true`"
":package_url" = "https://github.com/bensadeghi/DecisionTree.jl"
":package_name" = "DecisionTree"
":name" = "DecisionTreeClassifier"
":is_probabilistic" = "`true`"
":target_scitype" = "`MLJBase.Multiclass`"

[ScikitLearn.SVMLClassifier]
":input_is_multivariate" = "`true`"
":package_uuid" = "3646fa90-6ef7-5e7e-9f22-8aca16db6324"
":load_path" = "MLJModels.ScikitLearn_.SVMLClassifier"
":input_scitypes" = "`MLJBase.Continuous`"
":is_pure_julia" = "`false`"
":is_supervised" = "`true`"
":package_url" = "https://github.com/cstjean/ScikitLearn.jl"
":package_name" = "ScikitLearn"
":name" = "SVMLClassifier"
":is_probabilistic" = "`false`"
":target_scitype" = "`MLJBase.Multiclass`"

[ScikitLearn.SVMNuClassifier]
":input_is_multivariate" = "`true`"
":package_uuid" = "3646fa90-6ef7-5e7e-9f22-8aca16db6324"
":load_path" = "MLJModels.ScikitLearn_.SVMNuClassifier"
":input_scitypes" = "`MLJBase.Continuous`"
":is_pure_julia" = "`false`"
":is_supervised" = "`true`"
":package_url" = "https://github.com/cstjean/ScikitLearn.jl"
":package_name" = "ScikitLearn"
":name" = "SVMNuClassifier"
":is_probabilistic" = "`false`"
":target_scitype" = "`MLJBase.Multiclass`"

[ScikitLearn.SVMRegressor]
":input_is_multivariate" = "`true`"
":package_uuid" = "3646fa90-6ef7-5e7e-9f22-8aca16db6324"
":load_path" = "MLJModels.ScikitLearn_.SVMRegressor"
":input_scitypes" = "`MLJBase.Continuous`"
":is_pure_julia" = "`false`"
":is_supervised" = "`true`"
":package_url" = "https://github.com/cstjean/ScikitLearn.jl"
":package_name" = "ScikitLearn"
":name" = "SVMRegressor"
":is_probabilistic" = "`false`"
":target_scitype" = "`MLJBase.Continuous`"

[ScikitLearn.SVMClassifier]
":input_is_multivariate" = "`true`"
":package_uuid" = "3646fa90-6ef7-5e7e-9f22-8aca16db6324"
":load_path" = "MLJModels.ScikitLearn_.SVMClassifier"
":input_scitypes" = "`MLJBase.Continuous`"
":is_pure_julia" = "`false`"
":is_supervised" = "`true`"
":package_url" = "https://github.com/cstjean/ScikitLearn.jl"
":package_name" = "ScikitLearn"
":name" = "SVMClassifier"
":is_probabilistic" = "`false`"
":target_scitype" = "`MLJBase.Multiclass`"

[ScikitLearn.SVMLRegressor]
":input_is_multivariate" = "`true`"
":package_uuid" = "3646fa90-6ef7-5e7e-9f22-8aca16db6324"
":load_path" = "MLJModels.ScikitLearn_.SVMLRegressor"
":input_scitypes" = "`MLJBase.Continuous`"
":is_pure_julia" = "`false`"
":is_supervised" = "`true`"
":package_url" = "https://github.com/cstjean/ScikitLearn.jl"
":package_name" = "ScikitLearn"
":name" = "SVMLRegressor"
":is_probabilistic" = "`false`"
":target_scitype" = "`MLJBase.Continuous`"

[ScikitLearn.SVMNuRegressor]
":input_is_multivariate" = "`true`"
":package_uuid" = "3646fa90-6ef7-5e7e-9f22-8aca16db6324"
":load_path" = "MLJModels.ScikitLearn_.SVMNuRegressor"
":input_scitypes" = "`MLJBase.Continuous`"
":is_pure_julia" = "`false`"
":is_supervised" = "`true`"
":package_url" = "https://github.com/cstjean/ScikitLearn.jl"
":package_name" = "ScikitLearn"
":name" = "SVMNuRegressor"
":is_probabilistic" = "`false`"
":target_scitype" = "`MLJBase.Continuous`"

[Clustering.KMeans]
":input_is_multivariate" = "`true`"
":package_uuid" = "aaaa29a8-35af-508c-8bc3-b662a17a0fe5"
":load_path" = "MLJModels.Clustering_.KMeans"
":input_scitypes" = "`MLJBase.Continuous`"
":is_pure_julia" = "`true`"
":is_supervised" = "`false`"
":package_url" = "https://github.com/JuliaStats/Clustering.jl"
":package_name" = "Clustering"
":name" = "KMeans"
":output_is_multivariate" = "`true`"
":output_scitypes" = "`MLJBase.Continuous`"

[Clustering.KMedoids]
":input_is_multivariate" = "`true`"
":package_uuid" = "aaaa29a8-35af-508c-8bc3-b662a17a0fe5"
":load_path" = "MLJModels.Clustering_.KMedoids"
":input_scitypes" = "`MLJBase.Continuous`"
":is_pure_julia" = "`true`"
":is_supervised" = "`false`"
":package_url" = "https://github.com/JuliaStats/Clustering.jl"
":package_name" = "Clustering"
":name" = "KMedoids"
":output_is_multivariate" = "`true`"
":output_scitypes" = "`MLJBase.Continuous`"

[GLM.OLSRegressor]
":input_is_multivariate" = "`true`"
":package_uuid" = "38e38edf-8417-5370-95a0-9cbb8c7f171a"
":load_path" = "MLJModels.GLM_.OLSRegressor"
":input_scitypes" = "`MLJBase.Continuous`"
":is_pure_julia" = "`true`"
":is_supervised" = "`true`"
":package_url" = "https://github.com/JuliaStats/GLM.jl"
":package_name" = "GLM"
":name" = "OLSRegressor"
":is_probabilistic" = "`true`"
":target_scitype" = "`MLJBase.Continuous`"

[GLM.GLMCountRegressor]
":input_is_multivariate" = "`true`"
":package_uuid" = "38e38edf-8417-5370-95a0-9cbb8c7f171a"
":load_path" = "MLJModels.GLM_.GLMCountRegressor"
":input_scitypes" = "`MLJBase.Continuous`"
":is_pure_julia" = "`true`"
":is_supervised" = "`true`"
":package_url" = "https://github.com/JuliaStats/GLM.jl"
":package_name" = "GLM"
":name" = "GLMCountRegressor"
":is_probabilistic" = "`true`"
":target_scitype" = "`MLJBase.Count`"
